### ISSUE TITLE
Factory reset sets firmware password to default

### ISSUE THREAD

**Issue by szszszsz** [Nitrokey/nitrokey-storage-firmware#13]
Factory reset should not change firmware password.

Ubuntu 16.04, Firmware 0.36, https://github.com/Nitrokey/nitrokey-app/commit/5ec94e61990fa4c924670e33e1c4ca083e33c084

Scenario:
1. Change firmware password to `password`
2. Set update mode with `password` to confirm change
3. Flash device
4. Run Factory reset
5. Set update mode with `password` (would not work, but should)
6. Set update mode with `12345678` (would work)

**Comment by rudbo** [comment]
Disable resetting firmware password by factory reset
https://github.com/Nitrokey/nitrokey-storage-firmware/commit/ccb7554ad57265eecaaf7c4bcc712e496a91b3d0

**Comment by szszszsz** [comment]
Reboot command now does not resetting firmware password. Closing. 
Tested on Ubuntu 16.04 and firmware 0.38 with https://github.com/Nitrokey/nitrokey-app/commit/c8ea4064f2a6dc2b710efa78e024eeb98d688542
