### ISSUE TITLE
Support bigger OTP secrets (up to 40 bytes)

### ISSUE THREAD

**Issue by szszszsz** [Nitrokey/nitrokey-storage-firmware#23]
In NK Pro OTP secrets have been extended to support AWS.

Links:
- https://github.com/Nitrokey/nitrokey-pro-firmware/pull/29

**Comment by szszszsz** [comment]
Hi! It is (mostly), but both devices do not share the firmware code (yet).
I cannot say much at the moment. Implementation is in progress, so I would expect it will be in one of the next 3 releases. I do not know the exact schedule though.

**Comment by Jeeppler** [comment]
@szszszsz please update this issue, the moment you have more details about it.

**Comment by szszszsz** [comment]
@Jeeppler 
Feature is in the development, and most probably will arrive in the next firmware release.

**Comment by Jeeppler** [comment]
@szszszsz awesome, thank you.
