### ISSUE TITLE
smartcard.Exceptions.CardConnectionException: Unable to connect with protocol: T0 or T1. Sharing violation

### ISSUE THREAD

**Issue by Germano0** [Nitrokey/nitrokey-storage-firmware#25]
I am following [raymii's guide for deleting keys](https://raymii.org/s/articles/Nitrokey_Start_Getting_started_guide.html#Overwriting_(deleting)_keys_on_the_Nitrokey)

` $ python2 tool/gnuk_remove_keys.py -p`
returns
```
Admin password:
Traceback (most recent call last):
  File "tool/gnuk_remove_keys.py", line 112, in <module>
    main(passwd)
  File "tool/gnuk_remove_keys.py", line 86, in main
    gnuk.connection.connect()
  File "/usr/lib64/python2.7/site-packages/smartcard/CardConnectionDecorator.py", line 54, in connect
    self.component.connect(protocol, mode, disposition)
  File "/usr/lib64/python2.7/site-packages/smartcard/pcsc/PCSCCardConnection.py", line 128, in connect
    SCardGetErrorMessage(hresult))
smartcard.Exceptions.CardConnectionException: Unable to connect with protocol: T0 or T1. Sharing violation.
```
If I unplug and plug the key, I get different errors

```
$ python2 tool/gnuk_remove_keys.py -p
Admin password:
Token: Nitrokey Nitrokey Pro (xxxxxxxx) 00 00
ATR: xxxxxxxxx
Traceback (most recent call last):
  File "tool/gnuk_remove_keys.py", line 112, in <module>
    main(passwd)
  File "tool/gnuk_remove_keys.py", line 90, in main
    gnuk.cmd_verify(BY_ADMIN, passwd)
  File "tool/gnuk_remove_keys.py", line 54, in cmd_verify
    raise ValueError, ("%02x%02x" % (sw1, sw2))
ValueError: 6a88
```
`python-2.7.13-1.fc25.x86_64` `pyscard-1.9.0-5.fc25.x86_64` on Fedora 25

**Comment by jans23** [comment]
Do you have the latest firmware (v.045) installed?

**Comment by Germano0** [comment]
@jans23 Nitrokey App says firmware 0.8

**Comment by jans23** [comment]
It seems there is some confusion about the different Nitrokey models: You have a Nitrokey Pro but you followed instructions for Nitrokey Start and posted this issue in the project for Nitrokey Storage. If you want to delete keys on a Nitrokey Pro, you may want to [reset the device](https://www.nitrokey.com/de/documentation/frequently-asked-questions#how-to-reset-a-nitrokey) which deletes all three keys (and all other settings).

I'm closing this issue now. If you still have problems, please post a message in our [support forum](http://support.nitrokey.com/).
