### ISSUE TITLE
"New SD card" flag still set after SD being cleared

### ISSUE THREAD

**Issue by szszszsz** [Nitrokey/nitrokey-storage-firmware#28]
Nitrokey App v0.6.3
Storage v0.45
Ubuntu 16.10

Device is not clearing `new SD card` flag in its internal state after initialization. In consequence "New SD card found" message (depending directly on the byte-flag named similarly in the device's status) is still shown in about window after executing factory reset and clearing SD card with random data.

**Comment by szszszsz** [comment]
If it is up to the user to send the command clearing the SD card then please let me know, how the example usage looks like.
Should the user explicitly ask the device to accept current SD card?

**Comment by rudbo** [comment]
Yes, the user had to clear the message via the app

**Comment by szszszsz** [comment]
Thank you for clarification! This is not an issue then.
