### ISSUE TITLE
Please use github release feature for binary releases

### ISSUE THREAD

**Issue by CybotTM** [Nitrokey/nitrokey-storage-firmware#35]
Hi,

can you please use GitHub release feature for your binary releases?
It is easier to stay up to date and get informed about new releases.

> If you'd like to include binary files along with your release, such as compiled programs, drag and drop or select files manually in the binaries box.

https://help.github.com/articles/creating-releases/

Thank you.

**Comment by szszszsz** [comment]
Done for v0.46 - I guess it could be closed for now. Please reopen in case it would happen again.

Closing as invalid since this is not a 'source code issue'.
