### ISSUE TITLE
Set unencrypted volume writable with Admin PIN?

### ISSUE THREAD

**Issue by jans23** [Nitrokey/nitrokey-storage-firmware#48]
This idea needs to be confirmed!

Once the Nitrokey App is preinstalled on the unencrypted volume, it should be set read-only by default and only allow the Admin PIN to change it.

**Comment by szszszsz** [comment]
Currently User PIN is needed to change the state of the unencrypted volume and AFAIR it is in read-write by default.

**Comment by szszszsz** [comment]
Confirmed new command is working with Admin PIN with test firmware.

**Comment by jans23** [comment]
How can this be implement without letting users (of old NK App) run into backward-compatibility issues such as decreasing PIN counter? Perhaps remove the old command and add a new command instead of changing the existing one? Any other idea?

**Comment by szszszsz** [comment]
In v0.49 it was implemented in such way - command requiring User PIN always replies with 'wrong password' now (without decreasing the retry counter). The one requiring Admin PIN has new ID thus needing from host information about the protocol change and newer version of client applications. 
To have this decoupled, one way is to make the device an API server, similarly to web technologies but via USB (that is its commands and parameters could be listed and described). Perhaps part of it would be feasible, e.g. querying only for PIN type for given command.

**Comment by szszszsz** [comment]
I think this is fixed. Please close on confirmation.
