### ISSUE TITLE
Reboot command

### ISSUE THREAD

**Issue by szszszsz** [Nitrokey/nitrokey-storage-firmware#5]
I would make use of command which reboots stick. Currently I have to remove and insert again same device for achieving same 'start' state. Would that be possible to implement? Or, is there any other way?
I thought it could be possible through `dfu-programmer at32uc3a3256s start`, but it shows error it can not find any device.

**Comment by jans23** [comment]
@szszszsz Please elaborate what you mean with start state and what do you want to achieve actually.

**Comment by szszszsz** [comment]
@jans23 I would like to achieve using command same device state as it is in just after inserted to USB port. A command which would 'reboot' the OS on stick.

**Comment by jans23** [comment]
@szszszsz What in your scenario is the different to the start stage? For instance, would it be sufficient to lock the device (and reverse that PINs have been entered)?

**Comment by szszszsz** [comment]
@jans23 Particularly I would like to access to the unencrypted volume in case when stick 'removes the medium' from it. Reinserting the device solves the problem. Software solution would be better though.

**Comment by jans23** [comment]
@szszszsz Would a [USB port reset](https://askubuntu.com/questions/645/how-do-you-reset-a-usb-device-from-the-command-line) be an option?

**Comment by szszszsz** [comment]
@jans23 It would be great if this would work! I have tried sending messages to kernel but with no success. I will check it the source code.

**Comment by szszszsz** [comment]
Unfortunately, your second link is not working. About first one - looking at dmesg it sends reset command to controller, but device do not look like reset. 
I need the reboot command  to workaround https://github.com/Nitrokey/nitrokey-storage-firmware/issues/6.

**Comment by rudbo** [comment]
New HID cmd
CMD_RESET_STICK - 0x71, called with user password

https://github.com/Nitrokey/nitrokey-storage-firmware/commit/86d2aece982c9a180c36e3f47dc0ecac71a53cb6

**Comment by jans23** [comment]
@szszszsz Can you confirm that you don't need the reboot command anymore?

**Comment by szszszsz** [comment]
Currently I do not need it. It was only to avoid `prodinfo` side effects, but it was worked around anyway. It might be reverted for now and restored in case it would be needed to avoid any other side effects (but only for quick workarounds). It might be left as well since it does not look as security threat.

I have not added implementation of sending this command to application until now.

**Comment by szszszsz** [comment]
Since it has been added to firmware, this issue could be safely closed. I have left it open to test the command but had not time unfortunately.

**Comment by jans23** [comment]
I suggest to remove this feature to reduce the potential of any unforeseen sideeffects.

**Comment by rudbo** [comment]
Command in firmware removed
https://github.com/Nitrokey/nitrokey-storage-firmware/commit/ccb7554ad57265eecaaf7c4bcc712e496a91b3d0
