### ISSUE TITLE
New command: Blink LEDs

### ISSUE THREAD

**Issue by szszszsz** [Nitrokey/nitrokey-storage-firmware#50]
A command for blinking LEDs would be useful for signalizing from the host (Nitrokey App / libnitrokey) that the device needs action or has finished its time-requiring operation.

**Comment by Peacekeeper2000** [comment]
I would also support that :-)

**Comment by szszszsz** [comment]
Released in v0.52. After the function call device blinks infinitely.
Wink command available in C and C++ APIs.
