### ISSUE TITLE
Use memset_s

### ISSUE THREAD

**Issue by jans23** [Nitrokey/nitrokey-storage-firmware#64]
The code contains several occurrence of memset. memset could be optimized away by the compiler which is why memset_s should be used instead, for cases where a key or password or other confidential data has to be overwritten im RAM.

**Comment by NKelias** [comment]
`memset_s` seems to be a feature of C++11 and is not available on the AVR32 platform.

Alternatively, we could add a safe erase function as proposed here:
https://www.cryptologie.net/article/419/zeroing-memory-compiler-optimizations-and-memset_s/

**Comment by szszszsz** [comment]
Indeed, `volatile` should do the job. It is interesting to see double `volatile` in the [libsodium implementation]. 

[libsodium implementation]: https://github.com/jedisct1/libsodium/blob/be58b2e6664389d9c7993b55291402934b43b3ca/src/libsodium/sodium/utils.c#L78:L101
