### ISSUE TITLE
Nitrokey Storage's HOTP compatible with Heads?

### ISSUE THREAD

**Issue by tlaurion** [Nitrokey/nitrokey-storage-firmware#71]
Nitrokey Pro v2 supports HOTP as per Librem Key with this [commit](https://github.com/Nitrokey/nitrokey-pro-firmware/commit/664c11b3e6429551f1b21534efd8ae364047fa87)

Will this be ported to Nitrokey Storage 2?

----
When asked "Is the Nitrokey Storage 2 supporting Head's HOTP"?
Jan Suhr answered: "Yes, but id doesn't contain the Purism-specific verification feature yet."

**Comment by jans23** [comment]
We will add this feature sooner or later but don't have it scheduled yet.

**Comment by tlaurion** [comment]
@jans23 : Let us know [here](https://github.com/osresearch/heads/pull/426#issuecomment-419668917)! Some seem interested!

**Comment by szszszsz** [comment]
Hi!
Support is added with the release of v0.54 (with 7f41e1910949597cf32e96711d6800c0c9303550). Closing as done.
